import { describe, expect, test } from "vitest";
import { presets } from "./presets";
import { decodeChain } from "../core/decoder";
import { encodeChain } from "../core/encoder";

describe("Presets", () => {
  test("presets should match snapshot", { skip: true }, () => {
    expect(presets).toMatchSnapshot();
  });

  test("auto-generated presets survive the NUX encode/decode round trip", () => {
    const autoGeneratedPresets = presets.filter(
      (preset) => !preset.humanVerified,
    );

    expect(autoGeneratedPresets).toHaveLength(21);

    for (const preset of autoGeneratedPresets) {
      const encoded = encodeChain(preset.chain);
      const decoded = decodeChain(encoded.qrCode);
      const reencoded = encodeChain(decoded);

      expect(encoded.qrCode).toMatch(/^nux:\/\/MightyAmp:/);
      expect(encoded.bytes).toHaveLength(115);
      expect(decoded, preset.slug).toEqual(preset.chain);
      expect(reencoded.qrCode, preset.slug).toBe(encoded.qrCode);
    }
  });
});
