import { NuxMp3PresetIndex } from "lib/core/const";
import { BlockConfig, ChainItem } from "lib/core/interface";

export enum AmplifierType {
  JazzClean = "Jazz Clean",
  DeluxeRvb = "Deluxe Rvb",
  BassMate = "Bass Mate",
  Tweedy = "Tweedy",
  Hiwire = "Hiwire",
  CaliCrunch = "Cali Crunch",
  ClassA15 = "Class A15",
  ClassA30 = "Class A30",
  Plexi100 = "Plexi 100",
  Plexi45 = "Plexi 45",
  Brit800 = "Brit 800",
  Amp1987X50 = "1987 X 50",
  Slo100 = "SLO 100",
  FiremanHbe = "Fireman HBE",
  DualRect = "Dual Rect",
  DieVh4 = "Die VH4",
  MrZ38 = "Mr. Z38",
  SuperRvb = "Super Rvb",
  Agl = "AGL",
  Mld = "MLD",
  OptimaAir = "Optima Air",
  Stageman = "Stageman",
  TwinReverb = "Twin Reverb",
  VibroKing = "Vibro King",
  Budda = "Budda",
  BritBlues = "Brit Blues",
  MatchD30 = "Match D30",
  Brit2000 = "Brit 2000",
  UberHiGain = "Uber HiGain",
}

const TYPES: Record<AmplifierType, number> = {
  [AmplifierType.JazzClean]: 1,
  [AmplifierType.DeluxeRvb]: 2,
  [AmplifierType.BassMate]: 3,
  [AmplifierType.Tweedy]: 4,
  [AmplifierType.Hiwire]: 6,
  [AmplifierType.CaliCrunch]: 7,
  [AmplifierType.ClassA15]: 8,
  [AmplifierType.ClassA30]: 9,
  [AmplifierType.Plexi100]: 10,
  [AmplifierType.Plexi45]: 11,
  [AmplifierType.Brit800]: 12,
  [AmplifierType.Amp1987X50]: 13,
  [AmplifierType.Slo100]: 14,
  [AmplifierType.FiremanHbe]: 15,
  [AmplifierType.DualRect]: 16,
  [AmplifierType.DieVh4]: 17,
  [AmplifierType.MrZ38]: 20,
  [AmplifierType.SuperRvb]: 21,
  [AmplifierType.Agl]: 26,
  [AmplifierType.Mld]: 27,
  [AmplifierType.OptimaAir]: 28,
  [AmplifierType.Stageman]: 29,
  [AmplifierType.TwinReverb]: 5,
  [AmplifierType.VibroKing]: 18,
  [AmplifierType.Budda]: 19,
  [AmplifierType.BritBlues]: 22,
  [AmplifierType.MatchD30]: 23,
  [AmplifierType.Brit2000]: 24,
  [AmplifierType.UberHiGain]: 25,
};

export type AmplifierParams = ChainItem<
  AmplifierType.JazzClean,
  "Gain" | "Master" | "Bass" | "Middle" | "Treble" | "Bright"
>;

export const amplifier: BlockConfig = {
  encoderHeadIndex: NuxMp3PresetIndex.Head_iAMP,
  types: [
    {
      label: AmplifierType.JazzClean,
      realName: "Jazz Clean",
      encodeType: TYPES[AmplifierType.JazzClean],
      params: [
        {
          label: "Gain",
          encodeIndex: NuxMp3PresetIndex.AMP_Para1,
          // formatter: ValueFormatters.percentageMPPro
        },
        {
          label: "Master",
          encodeIndex: NuxMp3PresetIndex.AMP_Para2,
          // formatter: ValueFormatters.percentageMPPro
        },
        {
          label: "Bass",
          encodeIndex: NuxMp3PresetIndex.AMP_Para3,
          // formatter: ValueFormatters.percentageMPPro
        },
        {
          label: "Middle",
          encodeIndex: NuxMp3PresetIndex.AMP_Para4,
          // formatter: ValueFormatters.percentageMPPro
        },
        {
          label: "Treble",
          encodeIndex: NuxMp3PresetIndex.AMP_Para5,
          // formatter: ValueFormatters.percentageMPPro
        },
        {
          label: "Bright",
          encodeIndex: NuxMp3PresetIndex.AMP_Para6,
          // formatter: toggle
        },
      ],
    },
    {
      label: AmplifierType.DeluxeRvb,
      realName: "Fender Deluxe Reverb",
      encodeType: TYPES[AmplifierType.DeluxeRvb],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
      ],
    },
    {
      label: AmplifierType.BassMate,
      realName: "Fender Bassman",
      encodeType: TYPES[AmplifierType.BassMate],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Tweedy,
      realName: "Fender Tweed Deluxe",
      encodeType: TYPES[AmplifierType.Tweedy],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Tone", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Hiwire,
      realName: "Hiwatt DR103",
      encodeType: TYPES[AmplifierType.Hiwire],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.CaliCrunch,
      realName: "Mesa Boogie Mark I",
      encodeType: TYPES[AmplifierType.CaliCrunch],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.ClassA15,
      realName: "Vox AC15",
      encodeType: TYPES[AmplifierType.ClassA15],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Cut", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.ClassA30,
      realName: "Vox AC30",
      encodeType: TYPES[AmplifierType.ClassA30],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Cut", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Plexi100,
      realName: "Marshall JTM45 100W",
      encodeType: TYPES[AmplifierType.Plexi100],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Plexi45,
      realName: "Marshall JTM45 45W",
      encodeType: TYPES[AmplifierType.Plexi45],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Brit800,
      realName: "Marshall JCM800",
      encodeType: TYPES[AmplifierType.Brit800],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Amp1987X50,
      realName: "Marshall JCM1987X",
      encodeType: TYPES[AmplifierType.Amp1987X50],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Slo100,
      realName: "Soldano SLO-100",
      encodeType: TYPES[AmplifierType.Slo100],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.FiremanHbe,
      realName: "Friedman BE-100",
      encodeType: TYPES[AmplifierType.FiremanHbe],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.DualRect,
      realName: "Mesa Boogie Dual Rectifier",
      encodeType: TYPES[AmplifierType.DualRect],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.DieVh4,
      realName: "Diezel VH4",
      encodeType: TYPES[AmplifierType.DieVh4],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.MrZ38,
      realName: "Dr. Z MAZ 38",
      encodeType: TYPES[AmplifierType.MrZ38],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Cut", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.SuperRvb,
      realName: "Fender Super Reverb",
      encodeType: TYPES[AmplifierType.SuperRvb],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Bright", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Budda,
      realName: "Budda Superdrive",
      encodeType: TYPES[AmplifierType.Budda],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Cut", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.BritBlues,
      realName: "Marshall Bluesbreaker",
      encodeType: TYPES[AmplifierType.BritBlues],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.MatchD30,
      realName: "Matchless DC-30",
      encodeType: TYPES[AmplifierType.MatchD30],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Cut", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Brit2000,
      realName: "Marshall JCM2000",
      encodeType: TYPES[AmplifierType.Brit2000],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.UberHiGain,
      realName: "Bogner Uberschall",
      encodeType: TYPES[AmplifierType.UberHiGain],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Presence", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.Agl,
      realName: "Aguilar Tone Hammer",
      encodeType: TYPES[AmplifierType.Agl],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Mid Freq", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
      ],
    },
    {
      label: AmplifierType.Mld,
      realName: "NUX Melvin Lee Davis Preamp",
      encodeType: TYPES[AmplifierType.Mld],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Mid Freq", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
      ],
    },
    {
      label: AmplifierType.OptimaAir,
      realName: "NUX Optima Air",
      encodeType: TYPES[AmplifierType.OptimaAir],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
      ],
    },
    {
      label: AmplifierType.Stageman,
      realName: "NUX Stageman AC-50",
      encodeType: TYPES[AmplifierType.Stageman],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
      ],
    },
    {
      label: AmplifierType.TwinReverb,
      realName: "Fender Twin Reverb",
      encodeType: TYPES[AmplifierType.TwinReverb],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Bright", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
    {
      label: AmplifierType.VibroKing,
      realName: "Fender Vibro‑King",
      encodeType: TYPES[AmplifierType.VibroKing],
      params: [
        { label: "Gain", encodeIndex: NuxMp3PresetIndex.AMP_Para1 },
        { label: "Master", encodeIndex: NuxMp3PresetIndex.AMP_Para2 },
        { label: "Bass", encodeIndex: NuxMp3PresetIndex.AMP_Para3 },
        { label: "Middle", encodeIndex: NuxMp3PresetIndex.AMP_Para4 },
        { label: "Treble", encodeIndex: NuxMp3PresetIndex.AMP_Para5 },
        { label: "Bright", encodeIndex: NuxMp3PresetIndex.AMP_Para6 },
      ],
    },
  ],
};
